name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create
        id: step_one
        run: |
          touch .env
          echo "REACT_APP_API_KEY=XWWD4HUZ7NTFP3SIE2GE" >> .env
          echo "REACT_APP_ORG_ID=1538040099613" >> .env
          cat .env
