name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set the value
        id: step_one
        run: |
          touch .env
          echo "REACT_APP_API_KEY=aaa" >> .env
          cat .env
