name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run build
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_ORG_ID: ${{ secrets.REACT_APP_ORG_ID }}
      - name: Deploy
        run: |
          npm run deploy
